#!/usr/bin/env node
"use strict";

const fs = require("node:fs");
const path = require("node:path");

const PROJECT_DIR = __dirname;
const DEFAULT_OUTPUT = path.join(PROJECT_DIR, "index.html");
const TOM_SELECT_STYLESHEET_TAG =
  '<link rel="stylesheet" href="node_modules/tom-select/dist/css/tom-select.min.css">';
const STYLESHEET_TAG = '<link rel="stylesheet" href="production.css">';
const TOM_SELECT_SCRIPT_TAG =
  '<script src="node_modules/tom-select/dist/js/tom-select.base.min.js" defer></script>';
const SCRIPT_TAG = '<script src="production.js" defer></script>';

function readSource(name) {
  const sourcePath = path.join(PROJECT_DIR, name);
  try {
    return fs.readFileSync(sourcePath, "utf8");
  } catch (error) {
    throw new Error("Could not read " + sourcePath + ": " + error.message);
  }
}

function replaceOnce(document, marker, replacement) {
  const count = document.split(marker).length - 1;
  if (count !== 1) {
    throw new Error(
      "Expected exactly one " + JSON.stringify(marker) + " marker, found " + count,
    );
  }
  return document.replace(marker, replacement);
}

function validateCreatureNodes(creatureGroups) {
  let creatureCount = 0;

  for (const [faction, roots] of Object.entries(creatureGroups)) {
    if (!Array.isArray(roots)) {
      throw new Error("Creature faction " + faction + " is not an array");
    }

    for (const root of roots) {
      let creature = root;
      while (creature) {
        if (
          creature.horde_building !== undefined &&
          (typeof creature.horde_building !== "object" ||
            Array.isArray(creature.horde_building))
        ) {
          throw new Error(creature.name + " has an invalid horde_building");
        }

        creatureCount += 1;
        const upgrade = creature.upgraded_creature;
        if (upgrade != null && (typeof upgrade !== "object" || Array.isArray(upgrade))) {
          throw new Error(creature.name + " has an invalid upgraded_creature");
        }
        creature = upgrade || null;
      }
    }
  }

  if (creatureCount === 0) {
    throw new Error("creatures.json does not contain any creatures");
  }
}

function buildDocument() {
  let html = readSource("production.html");
  const tomSelectCss = readSource(
    "node_modules/tom-select/dist/css/tom-select.min.css",
  ).trimEnd();
  const css = readSource("production.css").trimEnd();
  const tomSelectJavascript = readSource(
    "node_modules/tom-select/dist/js/tom-select.base.min.js",
  ).trimEnd();
  const javascript = readSource("production.js").trimEnd();

  let creatureData;
  try {
    creatureData = JSON.parse(readSource("creatures.json"));
  } catch (error) {
    throw new Error("creatures.json is invalid: " + error.message);
  }

  const creatureGroups =
    creatureData.creatures &&
    typeof creatureData.creatures === "object" &&
    !Array.isArray(creatureData.creatures)
      ? creatureData.creatures
      : {};
  validateCreatureNodes(creatureGroups);
  if ((tomSelectCss + css).toLowerCase().includes("</style")) {
    throw new Error("A stylesheet contains a closing style tag");
  }
  if ((tomSelectJavascript + javascript).toLowerCase().includes("</script")) {
    throw new Error("A JavaScript source contains a closing script tag");
  }

  // Escaping the slash keeps embedded JSON from ever closing its script element.
  const embeddedJson = JSON.stringify(creatureData).replaceAll("</", "<\\/");

  html = replaceOnce(html, TOM_SELECT_STYLESHEET_TAG, "");
  html = replaceOnce(
    html,
    STYLESHEET_TAG,
    "<style>\n" + tomSelectCss + "\n" + css + "\n  </style>",
  );
  html = replaceOnce(html, TOM_SELECT_SCRIPT_TAG, "");
  html = replaceOnce(html, SCRIPT_TAG, "");
  html = replaceOnce(
    html,
    "</body>",
    '  <script id="creature-data" type="application/json">\n' +
      embeddedJson +
      "\n  </script>\n" +
      "  <script>\n" +
      tomSelectJavascript +
      "\n" +
      javascript +
      "\n  </script>\n" +
      "</body>",
  );
  html = replaceOnce(
    html,
    "<!doctype html>",
    "<!doctype html>\n" +
      "<!-- Generated by build_standalone.js; edit the source files instead. -->",
  );

  const lines = html.split(/\r\n|\r|\n/);
  if (lines.at(-1) === "") lines.pop();
  return lines.map((line) => line.trimEnd()).join("\n") + "\n";
}

function writeAtomic(output, document) {
  const resolvedOutput = path.resolve(output);
  const temporary = path.join(
    path.dirname(resolvedOutput),
    "." + path.basename(resolvedOutput) + ".tmp",
  );
  fs.mkdirSync(path.dirname(resolvedOutput), { recursive: true });
  try {
    fs.writeFileSync(temporary, document, "utf8");
    fs.renameSync(temporary, resolvedOutput);
  } finally {
    if (fs.existsSync(temporary)) fs.unlinkSync(temporary);
  }
}

function parseArgs(args) {
  let output = DEFAULT_OUTPUT;
  for (let index = 0; index < args.length; index += 1) {
    const argument = args[index];
    if (argument === "--output") {
      index += 1;
      if (index >= args.length) throw new Error("--output requires a file path");
      output = args[index];
    } else if (argument.startsWith("--output=")) {
      output = argument.slice("--output=".length);
      if (!output) throw new Error("--output requires a file path");
    } else if (argument === "--help" || argument === "-h") {
      console.log(
        "Bundle the production planner and its data into one offline HTML file.\n\n" +
          "Usage: node build_standalone.js [--output FILE]",
      );
      return null;
    } else {
      throw new Error("Unknown argument: " + argument);
    }
  }
  return output;
}

function main() {
  try {
    const output = parseArgs(process.argv.slice(2));
    if (output === null) return;
    const document = buildDocument();
    writeAtomic(output, document);
    const resolvedOutput = path.resolve(output);
    const size = fs.statSync(resolvedOutput).size.toLocaleString("en-US");
    console.log("Built " + resolvedOutput + " (" + size + " bytes)");
  } catch (error) {
    console.error("error: " + error.message);
    process.exitCode = 1;
  }
}

main();
