#!/usr/bin/env node
"use strict";

const fs = require("node:fs");
const path = require("node:path");

const PROJECT_DIR = __dirname;
const DEFAULT_OUTPUT = path.join(PROJECT_DIR, "index.html");
const STYLESHEET_TAG = '<link rel="stylesheet" href="production.css">';
const SCRIPT_TAG = '<script src="production.js" defer></script>';

function readSource(name) {
  const sourcePath = path.join(PROJECT_DIR, name);
  try {
    return fs.readFileSync(sourcePath, "utf8");
  } catch (error) {
    throw new Error("Could not read " + sourcePath + ": " + error.message);
  }
}

function replaceOnce(document, marker, replacement) {
  const count = document.split(marker).length - 1;
  if (count !== 1) {
    throw new Error(
      "Expected exactly one " + JSON.stringify(marker) + " marker, found " + count,
    );
  }
  return document.replace(marker, replacement);
}

function buildDocument() {
  let html = readSource("production.html");
  const css = readSource("production.css").trimEnd();
  const javascript = readSource("production.js").trimEnd();

  let creatureData;
  try {
    creatureData = JSON.parse(readSource("creatures.json"));
  } catch (error) {
    throw new Error("creatures.json is invalid: " + error.message);
  }

  const creatures = Array.isArray(creatureData.creatures) ? creatureData.creatures : [];
  if (creatureData.creature_count !== creatures.length) {
    throw new Error("creatures.json creature_count does not match its data");
  }
  if (css.toLowerCase().includes("</style")) {
    throw new Error("production.css contains a closing style tag");
  }
  if (javascript.toLowerCase().includes("</script")) {
    throw new Error("production.js contains a closing script tag");
  }

  // Escaping the slash keeps embedded JSON from ever closing its script element.
  const embeddedJson = JSON.stringify(creatureData).replaceAll("</", "<\\/");

  html = replaceOnce(html, STYLESHEET_TAG, "<style>\n" + css + "\n  </style>");
  html = replaceOnce(html, SCRIPT_TAG, "");
  html = replaceOnce(
    html,
    "</body>",
    '  <script id="creature-data" type="application/json">\n' +
      embeddedJson +
      "\n  </script>\n" +
      "  <script>\n" +
      javascript +
      "\n  </script>\n" +
      "</body>",
  );
  html = replaceOnce(
    html,
    "<!doctype html>",
    "<!doctype html>\n" +
      "<!-- Generated by build_standalone.js; edit the source files instead. -->",
  );

  const lines = html.split(/\r\n|\r|\n/);
  if (lines.at(-1) === "") lines.pop();
  return lines.map((line) => line.trimEnd()).join("\n") + "\n";
}

function writeAtomic(output, document) {
  const resolvedOutput = path.resolve(output);
  const temporary = path.join(
    path.dirname(resolvedOutput),
    "." + path.basename(resolvedOutput) + ".tmp",
  );
  fs.mkdirSync(path.dirname(resolvedOutput), { recursive: true });
  try {
    fs.writeFileSync(temporary, document, "utf8");
    fs.renameSync(temporary, resolvedOutput);
  } finally {
    if (fs.existsSync(temporary)) fs.unlinkSync(temporary);
  }
}

function parseArgs(args) {
  let output = DEFAULT_OUTPUT;
  for (let index = 0; index < args.length; index += 1) {
    const argument = args[index];
    if (argument === "--output") {
      index += 1;
      if (index >= args.length) throw new Error("--output requires a file path");
      output = args[index];
    } else if (argument.startsWith("--output=")) {
      output = argument.slice("--output=".length);
      if (!output) throw new Error("--output requires a file path");
    } else if (argument === "--help" || argument === "-h") {
      console.log(
        "Bundle the production planner and its data into one offline HTML file.\n\n" +
          "Usage: node build_standalone.js [--output FILE]",
      );
      return null;
    } else {
      throw new Error("Unknown argument: " + argument);
    }
  }
  return output;
}

function main() {
  try {
    const output = parseArgs(process.argv.slice(2));
    if (output === null) return;
    const document = buildDocument();
    writeAtomic(output, document);
    const resolvedOutput = path.resolve(output);
    const size = fs.statSync(resolvedOutput).size.toLocaleString("en-US");
    console.log("Built " + resolvedOutput + " (" + size + " bytes)");
  } catch (error) {
    console.error("error: " + error.message);
    process.exitCode = 1;
  }
}

main();
