#!/usr/bin/env python3
"""Bundle the production planner and its data into one offline HTML file."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path


PROJECT_DIR = Path(__file__).resolve().parent
DEFAULT_OUTPUT = PROJECT_DIR / "production-standalone.html"
STYLESHEET_TAG = '<link rel="stylesheet" href="production.css">'
SCRIPT_TAG = '<script src="production.js" defer></script>'


def read_source(name: str) -> str:
    path = PROJECT_DIR / name
    try:
        return path.read_text(encoding="utf-8")
    except OSError as error:
        raise RuntimeError(f"Could not read {path}: {error}") from error


def replace_once(document: str, marker: str, replacement: str) -> str:
    count = document.count(marker)
    if count != 1:
        raise RuntimeError(f"Expected exactly one {marker!r} marker, found {count}")
    return document.replace(marker, replacement, 1)


def build_document() -> str:
    html = read_source("production.html")
    css = read_source("production.css").rstrip()
    javascript = read_source("production.js").rstrip()

    try:
        creature_data = json.loads(read_source("creatures.json"))
    except json.JSONDecodeError as error:
        raise RuntimeError(f"creatures.json is invalid: {error}") from error

    if creature_data.get("creature_count") != len(creature_data.get("creatures", [])):
        raise RuntimeError("creatures.json creature_count does not match its data")
    if "</style" in css.casefold():
        raise RuntimeError("production.css contains a closing style tag")
    if "</script" in javascript.casefold():
        raise RuntimeError("production.js contains a closing script tag")

    # Escaping the slash keeps embedded JSON from ever closing its script element.
    embedded_json = json.dumps(
        creature_data,
        ensure_ascii=False,
        separators=(",", ":"),
    ).replace("</", "<\\/")

    html = replace_once(html, STYLESHEET_TAG, f"<style>\n{css}\n  </style>")
    html = replace_once(html, SCRIPT_TAG, "")
    html = replace_once(
        html,
        "</body>",
        (
            '  <script id="creature-data" type="application/json">\n'
            f"{embedded_json}\n"
            "  </script>\n"
            "  <script>\n"
            f"{javascript}\n"
            "  </script>\n"
            "</body>"
        ),
    )
    html = replace_once(
        html,
        "<!doctype html>",
        (
            "<!doctype html>\n"
            "<!-- Generated by build_standalone.py; edit the source files instead. -->"
        ),
    )
    return "\n".join(line.rstrip() for line in html.splitlines()) + "\n"


def write_atomic(output: Path, document: str) -> None:
    output = output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_name(f".{output.name}.tmp")
    try:
        temporary.write_text(document, encoding="utf-8")
        os.replace(temporary, output)
    finally:
        temporary.unlink(missing_ok=True)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"output file (default: {DEFAULT_OUTPUT.name})",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        document = build_document()
        write_atomic(args.output, document)
    except RuntimeError as error:
        print(f"error: {error}")
        return 1

    output = args.output.resolve()
    print(f"Built {output} ({output.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
